import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeCustomProvider } from "@/utils/providers/theme";
import { ReduxProvider } from "@/utils/providers/redux";
import { ReactQueryProvider } from "@/utils/providers/reactQuery";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <ReduxProvider>
          <ThemeCustomProvider>
            <body className={inter.className}>{children}</body>
          </ThemeCustomProvider>
        </ReduxProvider>
      </ReactQueryProvider>
    </html>
  );
}
